name: example
description: environment example
version: 0.0.1
homepage: "https://github.com/qjshuai/flutter_environment.git"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  environment:

dev_dependencies:
  flutter_test:
    sdk: flutter
