name: environment
description: app env
version: 0.0.9
homepage: "https://github.com/qjshuai/flutter_environment.git"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.8
  quiver: ^2.1.3
  flutter_bloc: ^6.0.5
  uuid: ^2.2.2
  shared_preferences: ^0.5.10
  dio: ^3.0.10
  connectivity: ^0.4.9+2
  fluttertoast: ^7.1.1
  provider: ^4.3.2+2
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: ^3.4.1